/**
 *
 *  PayCallback.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace pay_test
{
class PayPayment;

class PayCallback
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _payment_no;
        static const std::string _raw_body;
        static const std::string _signature;
        static const std::string _serial_no;
        static const std::string _verified;
        static const std::string _processed;
        static const std::string _received_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit PayCallback(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit PayCallback(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    PayCallback(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    PayCallback() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column payment_no  */
    ///Get the value of the column payment_no, returns the default value if the column is null
    const std::string &getValueOfPaymentNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPaymentNo() const noexcept;
    ///Set the value of the column payment_no
    void setPaymentNo(const std::string &pPaymentNo) noexcept;
    void setPaymentNo(std::string &&pPaymentNo) noexcept;

    /**  For column raw_body  */
    ///Get the value of the column raw_body, returns the default value if the column is null
    const std::string &getValueOfRawBody() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRawBody() const noexcept;
    ///Set the value of the column raw_body
    void setRawBody(const std::string &pRawBody) noexcept;
    void setRawBody(std::string &&pRawBody) noexcept;

    /**  For column signature  */
    ///Get the value of the column signature, returns the default value if the column is null
    const std::string &getValueOfSignature() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSignature() const noexcept;
    ///Set the value of the column signature
    void setSignature(const std::string &pSignature) noexcept;
    void setSignature(std::string &&pSignature) noexcept;
    void setSignatureToNull() noexcept;

    /**  For column serial_no  */
    ///Get the value of the column serial_no, returns the default value if the column is null
    const std::string &getValueOfSerialNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSerialNo() const noexcept;
    ///Set the value of the column serial_no
    void setSerialNo(const std::string &pSerialNo) noexcept;
    void setSerialNo(std::string &&pSerialNo) noexcept;
    void setSerialNoToNull() noexcept;

    /**  For column verified  */
    ///Get the value of the column verified, returns the default value if the column is null
    const bool &getValueOfVerified() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getVerified() const noexcept;
    ///Set the value of the column verified
    void setVerified(const bool &pVerified) noexcept;

    /**  For column processed  */
    ///Get the value of the column processed, returns the default value if the column is null
    const bool &getValueOfProcessed() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getProcessed() const noexcept;
    ///Set the value of the column processed
    void setProcessed(const bool &pProcessed) noexcept;

    /**  For column received_at  */
    ///Get the value of the column received_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfReceivedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getReceivedAt() const noexcept;
    ///Set the value of the column received_at
    void setReceivedAt(const ::trantor::Date &pReceivedAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    PayPayment getPayPayment(const drogon::orm::DbClientPtr &clientPtr) const;
    void getPayPayment(const drogon::orm::DbClientPtr &clientPtr,
                       const std::function<void(PayPayment)> &rcb,
                       const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<PayCallback>;
    friend drogon::orm::BaseBuilder<PayCallback, true, true>;
    friend drogon::orm::BaseBuilder<PayCallback, true, false>;
    friend drogon::orm::BaseBuilder<PayCallback, false, true>;
    friend drogon::orm::BaseBuilder<PayCallback, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<PayCallback>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<std::string> paymentNo_;
    std::shared_ptr<std::string> rawBody_;
    std::shared_ptr<std::string> signature_;
    std::shared_ptr<std::string> serialNo_;
    std::shared_ptr<bool> verified_;
    std::shared_ptr<bool> processed_;
    std::shared_ptr<::trantor::Date> receivedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "payment_no,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "raw_body,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "signature,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "serial_no,";
            ++parametersCount;
        }
        sql += "verified,";
        ++parametersCount;
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        sql += "processed,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        sql += "received_at,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace pay_test
} // namespace drogon_model
