/**
 *
 *  PayCallback.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PayCallback.h"
#include "PayPayment.h"
#include <drogon/utils/Utilities.h>
#include <string>
#include "orm_compat.h"

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::pay_test;

const std::string PayCallback::Cols::_id = "\"id\"";
const std::string PayCallback::Cols::_payment_no = "\"payment_no\"";
const std::string PayCallback::Cols::_raw_body = "\"raw_body\"";
const std::string PayCallback::Cols::_signature = "\"signature\"";
const std::string PayCallback::Cols::_serial_no = "\"serial_no\"";
const std::string PayCallback::Cols::_verified = "\"verified\"";
const std::string PayCallback::Cols::_processed = "\"processed\"";
const std::string PayCallback::Cols::_received_at = "\"received_at\"";
const std::string PayCallback::primaryKeyName = "id";
const bool PayCallback::hasPrimaryKey = true;
const std::string PayCallback::tableName = "\"pay_callback\"";

const std::vector<typename PayCallback::MetaData> PayCallback::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"payment_no","std::string","character varying",64,0,0,1},
{"raw_body","std::string","text",0,0,0,1},
{"signature","std::string","character varying",512,0,0,0},
{"serial_no","std::string","character varying",64,0,0,0},
{"verified","bool","boolean",1,0,0,1},
{"processed","bool","boolean",1,0,0,1},
{"received_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &PayCallback::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PayCallback::PayCallback(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["payment_no"].isNull())
        {
            paymentNo_=std::make_shared<std::string>(r["payment_no"].as<std::string>());
        }
        if(!r["raw_body"].isNull())
        {
            rawBody_=std::make_shared<std::string>(r["raw_body"].as<std::string>());
        }
        if(!r["signature"].isNull())
        {
            signature_=std::make_shared<std::string>(r["signature"].as<std::string>());
        }
        if(!r["serial_no"].isNull())
        {
            serialNo_=std::make_shared<std::string>(r["serial_no"].as<std::string>());
        }
        if(!r["verified"].isNull())
        {
            verified_=std::make_shared<bool>(r["verified"].as<bool>());
        }
        if(!r["processed"].isNull())
        {
            processed_=std::make_shared<bool>(r["processed"].as<bool>());
        }
        if(!r["received_at"].isNull())
        {
            auto timeStr = r["received_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                receivedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            paymentNo_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            rawBody_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            signature_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            serialNo_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            verified_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            processed_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                receivedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

PayCallback::PayCallback(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            paymentNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            rawBody_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            signature_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            serialNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            verified_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            processed_=std::make_shared<bool>(pJson[pMasqueradingVector[6]].asBool());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                receivedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

PayCallback::PayCallback(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("payment_no"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["payment_no"].isNull())
        {
            paymentNo_=std::make_shared<std::string>(pJson["payment_no"].asString());
        }
    }
    if(pJson.isMember("raw_body"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["raw_body"].isNull())
        {
            rawBody_=std::make_shared<std::string>(pJson["raw_body"].asString());
        }
    }
    if(pJson.isMember("signature"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["signature"].isNull())
        {
            signature_=std::make_shared<std::string>(pJson["signature"].asString());
        }
    }
    if(pJson.isMember("serial_no"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["serial_no"].isNull())
        {
            serialNo_=std::make_shared<std::string>(pJson["serial_no"].asString());
        }
    }
    if(pJson.isMember("verified"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["verified"].isNull())
        {
            verified_=std::make_shared<bool>(pJson["verified"].asBool());
        }
    }
    if(pJson.isMember("processed"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["processed"].isNull())
        {
            processed_=std::make_shared<bool>(pJson["processed"].asBool());
        }
    }
    if(pJson.isMember("received_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["received_at"].isNull())
        {
            auto timeStr = pJson["received_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                receivedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void PayCallback::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            paymentNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            rawBody_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            signature_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            serialNo_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            verified_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            processed_=std::make_shared<bool>(pJson[pMasqueradingVector[6]].asBool());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                receivedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void PayCallback::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("payment_no"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["payment_no"].isNull())
        {
            paymentNo_=std::make_shared<std::string>(pJson["payment_no"].asString());
        }
    }
    if(pJson.isMember("raw_body"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["raw_body"].isNull())
        {
            rawBody_=std::make_shared<std::string>(pJson["raw_body"].asString());
        }
    }
    if(pJson.isMember("signature"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["signature"].isNull())
        {
            signature_=std::make_shared<std::string>(pJson["signature"].asString());
        }
    }
    if(pJson.isMember("serial_no"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["serial_no"].isNull())
        {
            serialNo_=std::make_shared<std::string>(pJson["serial_no"].asString());
        }
    }
    if(pJson.isMember("verified"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["verified"].isNull())
        {
            verified_=std::make_shared<bool>(pJson["verified"].asBool());
        }
    }
    if(pJson.isMember("processed"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["processed"].isNull())
        {
            processed_=std::make_shared<bool>(pJson["processed"].asBool());
        }
    }
    if(pJson.isMember("received_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["received_at"].isNull())
        {
            auto timeStr = pJson["received_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                receivedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &PayCallback::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PayCallback::getId() const noexcept
{
    return id_;
}
void PayCallback::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename PayCallback::PrimaryKeyType & PayCallback::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &PayCallback::getValueOfPaymentNo() const noexcept
{
    static const std::string defaultValue = std::string();
    if(paymentNo_)
        return *paymentNo_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayCallback::getPaymentNo() const noexcept
{
    return paymentNo_;
}
void PayCallback::setPaymentNo(const std::string &pPaymentNo) noexcept
{
    paymentNo_ = std::make_shared<std::string>(pPaymentNo);
    dirtyFlag_[1] = true;
}
void PayCallback::setPaymentNo(std::string &&pPaymentNo) noexcept
{
    paymentNo_ = std::make_shared<std::string>(std::move(pPaymentNo));
    dirtyFlag_[1] = true;
}

const std::string &PayCallback::getValueOfRawBody() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rawBody_)
        return *rawBody_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayCallback::getRawBody() const noexcept
{
    return rawBody_;
}
void PayCallback::setRawBody(const std::string &pRawBody) noexcept
{
    rawBody_ = std::make_shared<std::string>(pRawBody);
    dirtyFlag_[2] = true;
}
void PayCallback::setRawBody(std::string &&pRawBody) noexcept
{
    rawBody_ = std::make_shared<std::string>(std::move(pRawBody));
    dirtyFlag_[2] = true;
}

const std::string &PayCallback::getValueOfSignature() const noexcept
{
    static const std::string defaultValue = std::string();
    if(signature_)
        return *signature_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayCallback::getSignature() const noexcept
{
    return signature_;
}
void PayCallback::setSignature(const std::string &pSignature) noexcept
{
    signature_ = std::make_shared<std::string>(pSignature);
    dirtyFlag_[3] = true;
}
void PayCallback::setSignature(std::string &&pSignature) noexcept
{
    signature_ = std::make_shared<std::string>(std::move(pSignature));
    dirtyFlag_[3] = true;
}
void PayCallback::setSignatureToNull() noexcept
{
    signature_.reset();
    dirtyFlag_[3] = true;
}

const std::string &PayCallback::getValueOfSerialNo() const noexcept
{
    static const std::string defaultValue = std::string();
    if(serialNo_)
        return *serialNo_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PayCallback::getSerialNo() const noexcept
{
    return serialNo_;
}
void PayCallback::setSerialNo(const std::string &pSerialNo) noexcept
{
    serialNo_ = std::make_shared<std::string>(pSerialNo);
    dirtyFlag_[4] = true;
}
void PayCallback::setSerialNo(std::string &&pSerialNo) noexcept
{
    serialNo_ = std::make_shared<std::string>(std::move(pSerialNo));
    dirtyFlag_[4] = true;
}
void PayCallback::setSerialNoToNull() noexcept
{
    serialNo_.reset();
    dirtyFlag_[4] = true;
}

const bool &PayCallback::getValueOfVerified() const noexcept
{
    static const bool defaultValue = bool();
    if(verified_)
        return *verified_;
    return defaultValue;
}
const std::shared_ptr<bool> &PayCallback::getVerified() const noexcept
{
    return verified_;
}
void PayCallback::setVerified(const bool &pVerified) noexcept
{
    verified_ = std::make_shared<bool>(pVerified);
    dirtyFlag_[5] = true;
}

const bool &PayCallback::getValueOfProcessed() const noexcept
{
    static const bool defaultValue = bool();
    if(processed_)
        return *processed_;
    return defaultValue;
}
const std::shared_ptr<bool> &PayCallback::getProcessed() const noexcept
{
    return processed_;
}
void PayCallback::setProcessed(const bool &pProcessed) noexcept
{
    processed_ = std::make_shared<bool>(pProcessed);
    dirtyFlag_[6] = true;
}

const ::trantor::Date &PayCallback::getValueOfReceivedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(receivedAt_)
        return *receivedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PayCallback::getReceivedAt() const noexcept
{
    return receivedAt_;
}
void PayCallback::setReceivedAt(const ::trantor::Date &pReceivedAt) noexcept
{
    receivedAt_ = std::make_shared<::trantor::Date>(pReceivedAt);
    dirtyFlag_[7] = true;
}

void PayCallback::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PayCallback::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "payment_no",
        "raw_body",
        "signature",
        "serial_no",
        "verified",
        "processed",
        "received_at"
    };
    return inCols;
}

void PayCallback::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getPaymentNo())
        {
            binder << getValueOfPaymentNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRawBody())
        {
            binder << getValueOfRawBody();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSignature())
        {
            binder << getValueOfSignature();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSerialNo())
        {
            binder << getValueOfSerialNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getVerified())
        {
            binder << getValueOfVerified();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getProcessed())
        {
            binder << getValueOfProcessed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getReceivedAt())
        {
            binder << getValueOfReceivedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PayCallback::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void PayCallback::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getPaymentNo())
        {
            binder << getValueOfPaymentNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRawBody())
        {
            binder << getValueOfRawBody();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSignature())
        {
            binder << getValueOfSignature();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSerialNo())
        {
            binder << getValueOfSerialNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getVerified())
        {
            binder << getValueOfVerified();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getProcessed())
        {
            binder << getValueOfProcessed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getReceivedAt())
        {
            binder << getValueOfReceivedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PayCallback::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPaymentNo())
    {
        ret["payment_no"]=getValueOfPaymentNo();
    }
    else
    {
        ret["payment_no"]=Json::Value();
    }
    if(getRawBody())
    {
        ret["raw_body"]=getValueOfRawBody();
    }
    else
    {
        ret["raw_body"]=Json::Value();
    }
    if(getSignature())
    {
        ret["signature"]=getValueOfSignature();
    }
    else
    {
        ret["signature"]=Json::Value();
    }
    if(getSerialNo())
    {
        ret["serial_no"]=getValueOfSerialNo();
    }
    else
    {
        ret["serial_no"]=Json::Value();
    }
    if(getVerified())
    {
        ret["verified"]=getValueOfVerified();
    }
    else
    {
        ret["verified"]=Json::Value();
    }
    if(getProcessed())
    {
        ret["processed"]=getValueOfProcessed();
    }
    else
    {
        ret["processed"]=Json::Value();
    }
    if(getReceivedAt())
    {
        ret["received_at"]=getReceivedAt()->toDbStringLocal();
    }
    else
    {
        ret["received_at"]=Json::Value();
    }
    return ret;
}

std::string PayCallback::toString() const
{
    return toJson().toStyledString();
}

Json::Value PayCallback::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPaymentNo())
            {
                ret[pMasqueradingVector[1]]=getValueOfPaymentNo();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getRawBody())
            {
                ret[pMasqueradingVector[2]]=getValueOfRawBody();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSignature())
            {
                ret[pMasqueradingVector[3]]=getValueOfSignature();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSerialNo())
            {
                ret[pMasqueradingVector[4]]=getValueOfSerialNo();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getVerified())
            {
                ret[pMasqueradingVector[5]]=getValueOfVerified();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getProcessed())
            {
                ret[pMasqueradingVector[6]]=getValueOfProcessed();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getReceivedAt())
            {
                ret[pMasqueradingVector[7]]=getReceivedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPaymentNo())
    {
        ret["payment_no"]=getValueOfPaymentNo();
    }
    else
    {
        ret["payment_no"]=Json::Value();
    }
    if(getRawBody())
    {
        ret["raw_body"]=getValueOfRawBody();
    }
    else
    {
        ret["raw_body"]=Json::Value();
    }
    if(getSignature())
    {
        ret["signature"]=getValueOfSignature();
    }
    else
    {
        ret["signature"]=Json::Value();
    }
    if(getSerialNo())
    {
        ret["serial_no"]=getValueOfSerialNo();
    }
    else
    {
        ret["serial_no"]=Json::Value();
    }
    if(getVerified())
    {
        ret["verified"]=getValueOfVerified();
    }
    else
    {
        ret["verified"]=Json::Value();
    }
    if(getProcessed())
    {
        ret["processed"]=getValueOfProcessed();
    }
    else
    {
        ret["processed"]=Json::Value();
    }
    if(getReceivedAt())
    {
        ret["received_at"]=getReceivedAt()->toDbStringLocal();
    }
    else
    {
        ret["received_at"]=Json::Value();
    }
    return ret;
}

bool PayCallback::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("payment_no"))
    {
        if(!validJsonOfField(1, "payment_no", pJson["payment_no"], err, true))
            return false;
    }
    else
    {
        err="The payment_no column cannot be null";
        return false;
    }
    if(pJson.isMember("raw_body"))
    {
        if(!validJsonOfField(2, "raw_body", pJson["raw_body"], err, true))
            return false;
    }
    else
    {
        err="The raw_body column cannot be null";
        return false;
    }
    if(pJson.isMember("signature"))
    {
        if(!validJsonOfField(3, "signature", pJson["signature"], err, true))
            return false;
    }
    if(pJson.isMember("serial_no"))
    {
        if(!validJsonOfField(4, "serial_no", pJson["serial_no"], err, true))
            return false;
    }
    if(pJson.isMember("verified"))
    {
        if(!validJsonOfField(5, "verified", pJson["verified"], err, true))
            return false;
    }
    if(pJson.isMember("processed"))
    {
        if(!validJsonOfField(6, "processed", pJson["processed"], err, true))
            return false;
    }
    if(pJson.isMember("received_at"))
    {
        if(!validJsonOfField(7, "received_at", pJson["received_at"], err, true))
            return false;
    }
    return true;
}
bool PayCallback::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PayCallback::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("payment_no"))
    {
        if(!validJsonOfField(1, "payment_no", pJson["payment_no"], err, false))
            return false;
    }
    if(pJson.isMember("raw_body"))
    {
        if(!validJsonOfField(2, "raw_body", pJson["raw_body"], err, false))
            return false;
    }
    if(pJson.isMember("signature"))
    {
        if(!validJsonOfField(3, "signature", pJson["signature"], err, false))
            return false;
    }
    if(pJson.isMember("serial_no"))
    {
        if(!validJsonOfField(4, "serial_no", pJson["serial_no"], err, false))
            return false;
    }
    if(pJson.isMember("verified"))
    {
        if(!validJsonOfField(5, "verified", pJson["verified"], err, false))
            return false;
    }
    if(pJson.isMember("processed"))
    {
        if(!validJsonOfField(6, "processed", pJson["processed"], err, false))
            return false;
    }
    if(pJson.isMember("received_at"))
    {
        if(!validJsonOfField(7, "received_at", pJson["received_at"], err, false))
            return false;
    }
    return true;
}
bool PayCallback::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PayCallback::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 512)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 512)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
PayPayment PayCallback::getPayPayment(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from pay_payment where payment_no = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *paymentNo_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return PayPayment(r[0]);
}

void PayCallback::getPayPayment(const DbClientPtr &clientPtr,
                                const std::function<void(PayPayment)> &rcb,
                                const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from pay_payment where payment_no = $1";
    *clientPtr << sql
               << *paymentNo_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(PayPayment(r[0]));
                    }
               }
               >> ecb;
}
